### ISSUE TITLE
Fix escaping of `` and ''

### ISSUE THREAD

**Issue by droundy** [droundy/paradigms#19]
This is for me to fix in the latex processor.

**Comment by droundy** [comment]
It turned out that mathjax was messing with the latex stored in innerHTML before we had a chance to render it.  I think I came up with a clean solution, which is to store the latex code in a data attribute (data-latex) instead, which then doesn't get touched.

A quick call to `grep -r latextorender templates/ | grep html` reveals some 20+ places where we'll need to make changes to put the latex into an attribute rather than the body.  An interesting question is whether to put the latex both places.  If someone has javascript disabled, showing raw latex might be better than nothing? But it hardly seems worth bloating the html files just for that.  For now render.html puts the latex in both places.

Currently I use innerHTML in cases where the data-latex attribute is undefined, which should preserve the current behavior during a transition, but I'd lean towards removing this conditional once we have switched the templates over to data-latex.

If this seems horrible, let me know.

**Comment by ColorCodeStudio** [comment]
This seems fine. 
Since I have a functional copy of this system here for testing can you tell me what I need to do to modify the other templates? Is it just as simple as adding the data-latex attribute? Doing so does not work on the activity_list.html template, so I'm suspecting there is more that I need to do?

**Comment by ColorCodeStudio** [comment]
Ignore that last comment.

**Comment by droundy** [comment]
This should be closed when we've switched all the templates to stick the latex information in the data-latex attribute, or if we come up with another fix.

**Comment by ColorCodeStudio** [comment]
done.
