### ISSUE TITLE
figure out permissions issue for latex_snippet.

### ISSUE THREAD

**Issue by droundy** [droundy/paradigms#2]
In commit 273ec52ac1f9119a682d3e376250512747fba850 I attempted to make the latex_snippet files (js and wasm) symlinks to another directory, so I could more easily automate the process of pushing changes to the wasm code to production.  But then the server couldn't access those files via symlink, so I quickly reverted the change.

Can you debug the permissions here? It'll be great to be able to just push the latex_snippets code.

**Comment by ColorCodeStudio** [comment]
I'll be back around 3:30-3:45, but gave your user sudo privileges on the server so you should be able to debug between now and then?

**Comment by droundy** [comment]
I think even with privileges I'm too inexperienced to debug this.  Not sure which log would have the error information.

**Comment by ColorCodeStudio** [comment]
Ok, can you tell me where you are trying to place the actual files? I'll 
see if I can create the links, replicate the error, and debug.

**Comment by droundy** [comment]
They're in /home/droundy/latex/pkg/

**Comment by ColorCodeStudio** [comment]
I sent an email on 2/12 about this, but I think we're going to have to use a post-receive or some other method to push into a directory fully accessible to apache. "Symbolic link not allowed or link target not accessible" Many methods tried to work around in our environment with no success so far.

**Comment by ColorCodeStudio** [comment]
I think we can close this, right?
