### ISSUE TITLE
Enable easy links with correct titles within the site 

### ISSUE THREAD

**Issue by droundy** [droundy/paradigms#26]
I'd like to enable creations of "correct" links to activities in particular, and probably other things.  These will be created from within latex, and I'm thinking something like `\url{/activities/19}` as the syntax within the latex.  This will currently work to create a link, but the result will look like `<a href="/activities/19">/activities/19</a>` where the user would like to see `<a href="/activities/19">Activity: Acting Out Current Density</a>`.

We could get the desired outcome by typing in latex `\href{/activities/19}{Activity: Acting Out Current Density}`, but that has two major risks.  One is that if the title of the activity is changed, this will need to be edited.  The other is that if the editor of this page typed the wrong number, the only way to notice that will be by actually clicking on the link and noticing that it goes to the wrong page.

So the question is how to achieve this.  Obviously it needs a database query to associate titles with numbers.  I could imagine either pre-processing the latex, or post-processing the HTML.  I'm not sure which is nicer.  Either could be done from javascript if we can access the database from javascript.  Or we could do pre-process on server prior to sending the latex to the browser.  Or a third option would be to embed a mapping of integers to titles into the javascript, so the data is available without a round-trip to the server.

I'm not sure which of these would be most feasible/desirable.  I sort of lean towards the javascript post-processing, since that could be done incrementally after the bulk of the page is visible.  But it definitely relies on being able to query the server to find out what the title of `/activity/19` is.

**Comment by droundy** [comment]
Note: another possibility would be to specify the activity title in the `\url{}`, and then have the javascript look up the link.  This would be prettier, but more fragile as we expect the title to change more often than the id.

**Comment by ColorCodeStudio** [comment]
I added a url /activities/title/[activity_id] (no trailing slash) that can be used to display only the title of a given activity. Let me know if this is suitable.

**Comment by droundy** [comment]
I think that could work pretty nicely with an iframes trick such as:

https://css-tricks.com/the-simplest-ways-to-handle-html-includes/#article-header-id-7

but I wonder if it would be hard to put the title at the end of the url, so it's

/activities/[activity_id]/title?

That would mean we could easily generalize this to add a /title at the end of most URLs to get the title, which could make generating internal links like this very consistent.

**Comment by ColorCodeStudio** [comment]
Ok, done. /activities/[activity_id]/title works.

**Comment by droundy** [comment]
I've attempted to make /about/title and /history/title work, but I think I've made a mistake, or django may need to be restarted to recognize the new URL.  Can you check out the stack trace on

https://paradigms.oregonstate.edu/about/title

and compare with the contents of pages/urls.py to see what needs doing?

**Comment by ColorCodeStudio** [comment]
Fixed. Just required querying the database on the page name / slug field rather than by primary key.

**Comment by droundy** [comment]
Thanks!
