### ISSUE TITLE
figure out svg/pdf conversion for problem sources

### ISSUE THREAD

**Issue by droundy** [droundy/paradigms#56]
Latex needs pdfs, web needs svgs.  What to do?

**Comment by ColorCodeStudio** [comment]
We can hide and show different media types using CSS based on whether it's going to screen or print. With this in mind, does it make sense to have the user upload one format and we convert to whatever is needed through Django?

**Comment by ColorCodeStudio** [comment]
Sorry, that was assuming we use wkhtmltopdf which renders a pdf from html. But I suppose it could also apply if we are converting latex directly to pdf using pandoc as well.

**Comment by droundy** [comment]
This issue is for when we support users downloading problem source.  We don't support that yet, so this should be postponed until we're working on it, probably summer.
